[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "anoma"
resolver = "2"
version = "0.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["ABCI", "ibc-vp-abci"]
# NOTE "dev" features that shouldn't be used in live networks are enabled by default for now
dev = []
ferveo-tpke = [
  "ferveo",
  "tpke",
  "ark-ec",
  "rand_core",
  "rand",
]
# for integration tests and test utilies
ibc-vp = [
  "ibc",
]
ibc-vp-abci = [
  "ibc-abci",
]
ibc-mocks = [
  "ibc/mocks",
]
ibc-mocks-abci = [
  "ibc-abci/mocks",
]
# for integration tests and test utilies
ABCI = [
  "ibc-proto-abci",
  "tendermint-stable",
  "tendermint-proto-abci",
]
ABCI-plus-plus = [
  "ibc-proto",
  "tendermint",
  "tendermint-proto",
]
testing = [
  "proptest",
  "rand",
  "rand_core",
  "tempfile",
]
wasm-runtime = [
  "loupe",
  "parity-wasm",
  "pwasm-utils",
  "wasmer-cache",
  "wasmer-compiler-singlepass",
  "wasmer-engine-dylib",
  "wasmer-engine-universal",
  "wasmer-vm",
  "wasmer",
]

[dependencies]
anoma_proof_of_stake = {path = "../proof_of_stake"}
ark-bls12-381 = {version = "0.3"}
ark-ec = {version = "0.3", optional = true}
ark-serialize = "0.3"
bech32 = "0.8.0"
bellman = {version = "0.11.1", features = ["groth16"]}
bls12_381 = {version = "0.6.0"}
borsh = "0.9.0"
chrono = "0.4.19"
# Using unreleased commit on top of version 0.5.0 that adds Sync to the CLruCache
clru = {git = "https://github.com/marmeladema/clru-rs.git", rev = "71ca566"}
derivative = "2.2.0"
ed25519-consensus = "1.2.0"
ferveo = {optional = true, git = "https://github.com/anoma/ferveo"}
ferveo-common = {git = "https://github.com/anoma/ferveo"}
getrandom = {version = "0.2", features = ["custom"]}
group = {version = "0.11.0"}
hex = "0.4.3"
tpke = {package = "group-threshold-cryptography", optional = true, git = "https://github.com/anoma/ferveo"}
# TODO using the same version of tendermint-rs as we do here.
ibc = {git = "https://github.com/heliaxdev/ibc-rs", branch = "yuji/v0.12.0_abcipp_v0.23.5", default-features = false, optional = true}
ibc-abci = {package = "ibc", git = "https://github.com/heliaxdev/ibc-rs", branch = "tomas/getrandom-no-js", default-features = false, optional = true}
ibc-proto = {git = "https://github.com/heliaxdev/ibc-rs", branch = "yuji/v0.12.0_abcipp_v0.23.5", default-features = false, optional = true}
ibc-proto-abci = {package = "ibc-proto", git = "https://github.com/heliaxdev/ibc-rs", branch = "tomas/getrandom-no-js", default-features = false, optional = true}
ics23 = "0.6.7"
itertools = "0.10.0"
jubjub = {version = "0.8.0"}
loupe = {version = "0.1.3", optional = true}
# masp_primitives = { git = "https://github.com/murisi/masp", branch = "murisi/masp-transaction3" }
masp_primitives = { git = "https://github.com/memasdeligeorgakis/masp", branch = "feat/000/remove_std_from_bip0039_dep" }
masp_proofs = { git = "https://github.com/murisi/masp", branch = "murisi/masp-transaction3" }
parity-wasm = {version = "0.42.2", optional = true}
proptest = {version = "1.0.0", optional = true}
prost = "0.9.0"
prost-types = "0.9.0"
pwasm-utils = {version = "0.18.0", optional = true}
rand = {version = "0.8", optional = true}
# TODO proptest rexports the RngCore trait but the re-implementations only work for version `0.8`. *sigh*
rand_core = {version = "0.6", optional = true}
rand_xorshift = {version = "0.3.0"}
rust_decimal = "1.14.3"
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.62"
sha2 = "0.9.3"
# We switch off "blake2b" because it cannot be compiled to wasm
sparse-merkle-tree = {git = "https://github.com/heliaxdev/sparse-merkle-tree", branch = "yuji/prost-0.9", default-features = false, features = ["std", "borsh"]}
tempfile = {version = "3.2.0", optional = true}
# temporarily using fork work-around for https://github.com/informalsystems/tendermint-rs/issues/971
tendermint = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "yuji/abcipp-v0.23.5", optional = true}
tendermint-proto = {git = "https://github.com/heliaxdev/tendermint-rs", branch = "yuji/abcipp-v0.23.5", optional = true}
tendermint-proto-abci = {package = "tendermint-proto", git = "https://github.com/heliaxdev/tendermint-rs", branch = "tomas/getrandom-no-js", optional = true}
tendermint-stable = {package = "tendermint", git = "https://github.com/heliaxdev/tendermint-rs", branch = "tomas/getrandom-no-js", optional = true}
thiserror = "1.0.30"
tracing = "0.1.30"
wasmer = {version = "=2.2.0", optional = true}
wasmer-cache = {version = "=2.2.0", optional = true}
wasmer-compiler-singlepass = {version = "=2.2.0", optional = true}
wasmer-engine-dylib = {version = "=2.2.0", optional = true}
wasmer-engine-universal = {version = "=2.2.0", optional = true}
wasmer-vm = {version = "2.2.0", optional = true}
wasmparser = "0.83.0"

[dev-dependencies]
assert_matches = "1.5.0"
byte-unit = "4.0.13"
pretty_assertions = "0.7.2"
proptest = "1.0.0"
test-log = {version = "0.2.7", default-features = false, features = ["trace"]}
tracing-subscriber = {version = "0.3.7", default-features = false, features = ["env-filter", "fmt"]}

[build-dependencies]
tonic-build = "0.6.0"
